version: 2.1

executors:
  android-flutter:
     docker:
     - image: circleci/android:api-28-alpha
     environment:
       JVM_OPTS: -Xmx3200m
jobs:
  build_deploy:
    executor: android-flutter
    steps:
      - checkout
      - restore_cache:
          key: jars-{{ checksum "build.gradle" }}-{{ checksum  "app/build.gradle" }}
      - run:
          name: Install fastlane
          command: bundle install
      - save_cache:
          paths:
            - ~/.gradle
          key: jars-{{ checksum "build.gradle" }}-{{ checksum  "app/build.gradle" }}
      - run:
          name: Run the unit tests
          command: bundle exec fastlane build    

workflows:
  deploy:
    jobs:
      - beta_deploy:
          filters:
            branches:
              only: circleci-project-setup
